version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_shop_app_admin
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb+srv://00356119:pass123@next-shop-app.ff2jmzt.mongodb.net/?retryWrites=true&w=majority&appName=next-shop-app
    volumes:
      - .:/app
      - /app/node_modules
